services:
  frontend:
    build: ./frontend/
    ports:
      - "3001:3000"
    volumes:
     - ./frontend/node_modules:/app/node_modules
     - ./frontend/public:/app/public
     - ./frontend/src:/app/src
    container_name: frontend
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm start
  backend:
    build: ./backend/
    container_name: backend
    volumes:
      - ./backend:/src
    ports:
      - "2000:80"    
    environment:
      - DEBUG=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
